### ISSUE TITLE
generate_actions is not defined

### ISSUE THREAD

**Issue by michaelaye** [Novetta/lib2nbdev#7]
Not sure if I found something not implemented yet, maybe?

```bash
$ convert_lib                                                                                                                      (py38) 
Checking for a settings.ini...
settings.ini already exists, going off existing version
Gathering files...
4 modules found in the library
Writing notebooks to /home/maye/Dropbox/src/pymcs/notebooks...
Initializing documentation foundation...████████████████████████████████████████| 100.00% [4/4 00:00<00:00]
pymcs successfully converted!
Would you like to setup this project to be pip installable and configure a setup.py? (0/1)1
Project is configured for pypi, please see `setup.py` for any advanced configurations
Would you like to setup the automated Github workflow that nbdev provides? (0/1)1
Traceback (most recent call last):
  File "/home/maye/miniconda3/envs/py38/bin/convert_lib", line 8, in <module>
    sys.exit(convert_lib())
  File "/home/maye/miniconda3/envs/py38/lib/python3.8/site-packages/fastcore/script.py", line 105, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/maye/miniconda3/envs/py38/lib/python3.8/site-packages/lib2nbdev/convert.py", line 223, in convert_lib
    generate_actions()
NameError: name 'generate_actions' is not defined
```
version 0.0.6

**Comment by muellerzr** [comment]
Fixed with 0.0.7, thanks!
