### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'cfg_path' and 'cfg_name'

### ISSUE THREAD

**Issue by hugocool** [Novetta/lib2nbdev#8]
When I run convert_lib in bash I get the following error:
```
Checking for a settings.ini...
settings.ini already exists, going off existing version
Gathering files...
12 modules found in the library
Traceback (most recent call last):
  File "/workspace/.pip-modules/bin/convert_lib", line 8, in <module>
    sys.exit(convert_lib())
  File "/workspace/.pip-modules/lib/python3.8/site-packages/fastcore/script.py", line 107, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/workspace/.pip-modules/lib/python3.8/site-packages/lib2nbdev/convert.py", line 145, in convert_lib
    nb_path = Config().path('nbs_path')
TypeError: __init__() missing 2 required positional arguments: 'cfg_path' and 'cfg_name'
```

**Comment by muellerzr** [comment]
Fixed, releasing a version today

**Comment by Torvaney** [comment]
Thanks for developing this tool!

I am getting the same error as above with lib2nbdev v0.0.9. Is this expected?

**Comment by muellerzr** [comment]
Can you share your version of `fastcore` please? `pip show fastcore`

**Comment by Torvaney** [comment]
```
Name: fastcore
Version: 1.3.26
Summary: Python supercharged for fastai development
Home-page: https://github.com/fastai/fastcore/tree/master/
Author: Jeremy Howard and Sylvain Gugger
Author-email: infos@fast.ai
License: Apache Software License 2.0
Location: /Users/ben/code/milan/possession-value/venv/lib/python3.7/site-packages
Requires: packaging, pip
Required-by: nbdev, lib2nbdev, ghapi, fastrelease
```

Do I need to update?

**Comment by Torvaney** [comment]
FWIW, the conversion seems to work fine using this fork: https://github.com/butchtm/lib2nbdev/commit/098630411f7616cdae595ccbcd7899449e889f4d

**Comment by Torvaney** [comment]
Awesome. Thanks again for this great tool!

**Comment by muellerzr** [comment]
@Torvaney lib2nbdev v 0.0.10 is out now on pypi, includes the fix
